# Provenance (reproducibility)

Six months after you make a figure, the question is always the same: *which snapshot, which
Mera version, what units produced this?* `provenance` answers it. It reads the metadata every
Mera result already carries (its `InfoType`) and returns a compact, **deterministic** record
you can print, compare, or stamp onto a figure or a FITS header.

!!! note "One part of a larger picture"
    A provenance record says what produced a number. It does not, by itself, let someone rebuild
    the software that produced it. For that you also need the package versions pinned in a Julia
    project. [Reproducibility](reproducibility.md) collects the four pieces, the project, this
    record, the published formula behind each quantity, and the test simulations with known
    answers, and shows them working together.


In [1]:
# Example-data root. Point this at your own simulation folder, or set the
# MERA_EXAMPLES environment variable; every path below is built from it.
MERA_EXAMPLES = get(ENV, "MERA_EXAMPLES", "/Volumes/FASTStorage/Simulations/Mera-Tests");

using Mera
info = getinfo(300, joinpath(MERA_EXAMPLES, "RAMSES/mw_L10"))
gas  = gethydro(info);

[ Info: Precompiling Mera [02f895e8-fdb1-4346-8fe6-c721699f5126](cache misses: include_dependency fsize change (5), dep missing source (1), mismatched flags (3))


[ Info: Precompiling Mera [02f895e8-fdb1-4346-8fe6-c721699f5126] (cache misses: include_dependency fsize change (10), dep missing source (2), mismatched flags (6))



SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up



*__   __ _______ ______   _______ 


|  |_|  |       |    _ | |   _   |
|       |    ___|   | || |  |_|  |
|       |   |___|   |_||_|       |
|       |    ___|    __  |       |
| ||_|| |   |___|   |  | |   _   |
|_|   |_|_______|___|  |_|__| |__|
Mera v1.8.0 | Julia 1.12.7 | 4 threads

[Mera]: 2026-09-11T08:44:24.298



Code: 

RAMSES
output [300] summary:
mtime: 2023-04-09T05:34:09
ctime: 2025-06-21T18:31:24.020
simulation time: 445.89 [Myr]
boxlen: 48.0 [kpc]
ncpu: 640
ndim: 3
cosmological:  false
-------------------------------------------------------
amr:           true
level(s): 6 - 10 --> cellsize(s): 750.0 [pc] - 46.88 [pc]
-------------------------------------------------------
hydro:         true
hydro-variables:  7

  --> (:rho, :vx, :vy, :vz, :p, :scalar_00, :scalar_01)
hydro-descriptor: (:density, :velocity_x, :velocity_y, :velocity_z, :pressure, :scalar_00, :scalar_01)
γ: 1.6667
-------------------------------------------------------
gravity:       true
gravity-variables: (:epot, :ax, :ay, :az)
-------------------------------------------------------
particles:     true
- Nstars:   5.445150e+05 


particle-variables: 7  --> (:vx, :vy, :vz, :mass, :family, :tag, :birth)
particle-descriptor: (:position_x, :position_y, :position_z, :velocity_x, :velocity_y, :velocity_z, :mass, :identity, :levelp, :family, :tag, :birth_time)
-------------------------------------------------------
rt:            false
clumps:           false
-------------------------------------------------------
namelist-file: (

"&COOLING_PARAMS", "&SF_PARAMS", "&AMR_PARAMS", "&BOUNDARY_PARAMS", "&OUTPUT_PARAMS", "&POISSON_PARAMS", "&RUN_PARAMS", "&FEEDBACK_PARAMS", "&HYDRO_PARAMS", "&INIT_PARAMS", "&REFINE_PARAMS")
-------------------------------------------------------
boundaries:       not periodic (&BOUNDARY_PARAMS closes x, y, z)
timer-file:       true
compilation-file: false
makefile:         true
patchfile:        true

[Mera]: Get hydro data: 2026-09-11T08:44:26.143



Key vars=(:level, :cx, :cy, :cz)


Using var(s)=(1, 2, 3, 4, 5, 6, 7) = (:rho, :vx, :vy, :vz, :p, :scalar_00, :scalar_01) 

domain:
xmin::xmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
ymin::ymax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
zmin::zmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]

📊 Processing Configuration:


   Total CPU files available: 640
   Files to be processed: 640
   Compute threads: 4
   GC threads: 4



Processing files:   0%|                                                  |  ETA: N/A (  N/A  s/it)

Processing files:   1%|▌                                                 |  ETA: 0:01:32 ( 0.15  s/it)

Processing files:   2%|▉                                                 |  ETA: 0:01:10 ( 0.11  s/it)

Processing files:   2%|█▏                                                |  ETA: 0:01:00 (95.47 ms/it)

Processing files:   3%|█▍                                                |  ETA: 0:00:54 (87.26 ms/it)

Processing files:   4%|██                                                |  ETA: 0:00:44 (71.28 ms/it)

Processing files:   4%|██▎                                               |  ETA: 0:00:43 (69.63 ms/it)

Processing files:   5%|██▋                                               |  ETA: 0:00:40 (66.18 ms/it)

Processing files:   6%|██▊                                               |  ETA: 0:00:38 (63.54 ms/it)

Processing files:   6%|███                                               |  ETA: 0:00:38 (63.37 ms/it)

Processing files:   7%|███▎                                              |  ETA: 0:00:36 (59.96 ms/it)

Processing files:   7%|███▋                                              |  ETA: 0:00:33 (55.76 ms/it)

Processing files:   8%|████                                              |  ETA: 0:00:31 (52.97 ms/it)

Processing files:   9%|████▍                                             |  ETA: 0:00:30 (51.05 ms/it)

Processing files:  10%|████▉                                             |  ETA: 0:00:28 (48.46 ms/it)

Processing files:  10%|█████▏                                            |  ETA: 0:00:27 (47.56 ms/it)

Processing files:  11%|█████▍                                            |  ETA: 0:00:27 (47.08 ms/it)

Processing files:  12%|█████▊                                            |  ETA: 0:00:26 (45.29 ms/it)

Processing files:  12%|██████▏                                           |  ETA: 0:00:25 (44.39 ms/it)

Processing files:  13%|██████▍                                           |  ETA: 0:00:25 (44.44 ms/it)

Processing files:  14%|███████                                           |  ETA: 0:00:23 (42.35 ms/it)

Processing files:  15%|███████▌                                          |  ETA: 0:00:22 (41.25 ms/it)

Processing files:  16%|████████                                          |  ETA: 0:00:22 (40.02 ms/it)

Processing files:  17%|████████▍                                         |  ETA: 0:00:21 (39.35 ms/it)

Processing files:  17%|████████▋                                         |  ETA: 0:00:21 (39.74 ms/it)

Processing files:  20%|██████████▎                                       |  ETA: 0:00:19 (37.48 ms/it)

Processing files:  21%|██████████▋                                       |  ETA: 0:00:19 (37.07 ms/it)

Processing files:  22%|███████████▏                                      |  ETA: 0:00:18 (36.24 ms/it)

Processing files:  23%|███████████▌                                      |  ETA: 0:00:18 (35.92 ms/it)

Processing files:  24%|████████████                                      |  ETA: 0:00:17 (35.76 ms/it)

Processing files:  25%|████████████▍                                     |  ETA: 0:00:17 (35.04 ms/it)

Processing files:  26%|████████████▊                                     |  ETA: 0:00:17 (34.82 ms/it)

Processing files:  27%|█████████████▍                                    |  ETA: 0:00:16 (34.23 ms/it)

Processing files:  28%|█████████████▉                                    |  ETA: 0:00:15 (33.46 ms/it)

Processing files:  29%|██████████████▎                                   |  ETA: 0:00:15 (33.31 ms/it)

Processing files:  29%|██████████████▊                                   |  ETA: 0:00:15 (32.96 ms/it)

Processing files:  30%|███████████████                                   |  ETA: 0:00:15 (32.83 ms/it)

Processing files:  31%|███████████████▌                                  |  ETA: 0:00:14 (32.69 ms/it)

Processing files:  32%|███████████████▉                                  |  ETA: 0:00:14 (32.45 ms/it)

Processing files:  32%|████████████████▎                                 |  ETA: 0:00:14 (32.18 ms/it)

Processing files:  33%|████████████████▋                                 |  ETA: 0:00:14 (32.00 ms/it)

Processing files:  34%|█████████████████                                 |  ETA: 0:00:14 (32.03 ms/it)

Processing files:  35%|█████████████████▌                                |  ETA: 0:00:13 (31.65 ms/it)

Processing files:  36%|█████████████████▉                                |  ETA: 0:00:13 (31.86 ms/it)

Processing files:  37%|██████████████████▍                               |  ETA: 0:00:13 (31.62 ms/it)

Processing files:  38%|██████████████████▊                               |  ETA: 0:00:13 (31.54 ms/it)

Processing files:  38%|███████████████████                               |  ETA: 0:00:12 (31.47 ms/it)

Processing files:  39%|███████████████████▍                              |  ETA: 0:00:12 (31.74 ms/it)

Processing files:  40%|███████████████████▉                              |  ETA: 0:00:12 (31.59 ms/it)

Processing files:  41%|████████████████████▎                             |  ETA: 0:00:12 (31.36 ms/it)

Processing files:  41%|████████████████████▊                             |  ETA: 0:00:12 (31.33 ms/it)

Processing files:  42%|█████████████████████▏                            |  ETA: 0:00:12 (31.20 ms/it)

Processing files:  43%|█████████████████████▍                            |  ETA: 0:00:11 (31.17 ms/it)

Processing files:  43%|█████████████████████▋                            |  ETA: 0:00:11 (31.30 ms/it)

Processing files:  44%|█████████████████████▊                            |  ETA: 0:00:11 (31.54 ms/it)

Processing files:  45%|██████████████████████▎                           |  ETA: 0:00:11 (31.40 ms/it)

Processing files:  45%|██████████████████████▋                           |  ETA: 0:00:11 (31.50 ms/it)

Processing files:  46%|██████████████████████▊                           |  ETA: 0:00:11 (31.63 ms/it)

Processing files:  46%|███████████████████████▎                          |  ETA: 0:00:11 (31.82 ms/it)

Processing files:  48%|███████████████████████▊                          |  ETA: 0:00:11 (32.29 ms/it)

Processing files:  50%|█████████████████████████▏                        |  ETA: 0:00:10 (32.48 ms/it)

Processing files:  51%|█████████████████████████▍                        |  ETA: 0:00:10 (32.58 ms/it)

Processing files:  52%|█████████████████████████▊                        |  ETA: 0:00:10 (32.72 ms/it)

Processing files:  52%|██████████████████████████                        |  ETA: 0:00:10 (32.94 ms/it)

Processing files:  53%|██████████████████████████▊                       |  ETA: 0:00:10 (33.01 ms/it)

Processing files:  54%|███████████████████████████                       |  ETA: 0:00:10 (33.09 ms/it)

Processing files:  55%|███████████████████████████▎                      |  ETA: 0:00:10 (33.24 ms/it)

Processing files:  55%|███████████████████████████▋                      |  ETA: 0:00:10 (33.29 ms/it)

Processing files:  56%|███████████████████████████▉                      |  ETA: 0:00:09 (33.43 ms/it)

Processing files:  56%|████████████████████████████▏                     |  ETA: 0:00:09 (33.47 ms/it)

Processing files:  57%|████████████████████████████▌                     |  ETA: 0:00:09 (33.38 ms/it)

Processing files:  58%|████████████████████████████▊                     |  ETA: 0:00:09 (33.32 ms/it)

Processing files:  58%|█████████████████████████████▏                    |  ETA: 0:00:09 (33.17 ms/it)

Processing files:  59%|█████████████████████████████▌                    |  ETA: 0:00:09 (33.08 ms/it)

Processing files:  60%|█████████████████████████████▊                    |  ETA: 0:00:09 (33.01 ms/it)

Processing files:  60%|██████████████████████████████▏                   |  ETA: 0:00:08 (32.96 ms/it)

Processing files:  61%|██████████████████████████████▌                   |  ETA: 0:00:08 (32.88 ms/it)

Processing files:  62%|██████████████████████████████▉                   |  ETA: 0:00:08 (32.76 ms/it)

Processing files:  62%|███████████████████████████████▏                  |  ETA: 0:00:08 (32.80 ms/it)

Processing files:  63%|███████████████████████████████▌                  |  ETA: 0:00:08 (32.74 ms/it)

Processing files:  64%|███████████████████████████████▉                  |  ETA: 0:00:08 (32.77 ms/it)

Processing files:  65%|████████████████████████████████▊                 |  ETA: 0:00:07 (32.41 ms/it)

Processing files:  66%|█████████████████████████████████▏                |  ETA: 0:00:07 (32.38 ms/it)

Processing files:  67%|█████████████████████████████████▍                |  ETA: 0:00:07 (32.40 ms/it)

Processing files:  68%|█████████████████████████████████▊                |  ETA: 0:00:07 (32.26 ms/it)

Processing files:  68%|██████████████████████████████████▏               |  ETA: 0:00:07 (32.16 ms/it)

Processing files:  69%|██████████████████████████████████▌               |  ETA: 0:00:06 (32.03 ms/it)

Processing files:  70%|██████████████████████████████████▉               |  ETA: 0:00:06 (31.92 ms/it)

Processing files:  71%|███████████████████████████████████▎              |  ETA: 0:00:06 (31.83 ms/it)

Processing files:  72%|███████████████████████████████████▊              |  ETA: 0:00:06 (31.85 ms/it)

Processing files:  74%|████████████████████████████████████▊             |  ETA: 0:00:05 (31.50 ms/it)

Processing files:  74%|█████████████████████████████████████▎            |  ETA: 0:00:05 (31.41 ms/it)

Processing files:  75%|█████████████████████████████████████▊            |  ETA: 0:00:05 (31.20 ms/it)

Processing files:  77%|██████████████████████████████████████▎           |  ETA: 0:00:05 (30.98 ms/it)

Processing files:  78%|██████████████████████████████████████▊           |  ETA: 0:00:04 (30.89 ms/it)

Processing files:  79%|███████████████████████████████████████▎          |  ETA: 0:00:04 (30.77 ms/it)

Processing files:  80%|███████████████████████████████████████▊          |  ETA: 0:00:04 (30.67 ms/it)

Processing files:  80%|████████████████████████████████████████▎         |  ETA: 0:00:04 (30.56 ms/it)

Processing files:  81%|████████████████████████████████████████▋         |  ETA: 0:00:04 (30.58 ms/it)

Processing files:  82%|█████████████████████████████████████████         |  ETA: 0:00:04 (30.49 ms/it)

Processing files:  83%|█████████████████████████████████████████▍        |  ETA: 0:00:03 (30.41 ms/it)

Processing files:  84%|█████████████████████████████████████████▊        |  ETA: 0:00:03 (30.35 ms/it)

Processing files:  84%|██████████████████████████████████████████        |  ETA: 0:00:03 (30.52 ms/it)

Processing files:  87%|███████████████████████████████████████████▌      |  ETA: 0:00:03 (30.15 ms/it)

Processing files:  88%|███████████████████████████████████████████▉      |  ETA: 0:00:02 (30.26 ms/it)

Processing files:  89%|████████████████████████████████████████████▊     |  ETA: 0:00:02 (30.03 ms/it)

Processing files:  90%|█████████████████████████████████████████████▏    |  ETA: 0:00:02 (29.98 ms/it)

Processing files:  91%|█████████████████████████████████████████████▋    |  ETA: 0:00:02 (29.85 ms/it)

Processing files:  92%|██████████████████████████████████████████████    |  ETA: 0:00:02 (29.82 ms/it)

Processing files:  93%|██████████████████████████████████████████████▍   |  ETA: 0:00:01 (29.80 ms/it)

Processing files:  93%|██████████████████████████████████████████████▋   |  ETA: 0:00:01 (29.80 ms/it)

Processing files:  94%|███████████████████████████████████████████████   |  ETA: 0:00:01 (29.79 ms/it)

Processing files:  95%|███████████████████████████████████████████████▍  |  ETA: 0:00:01 (29.74 ms/it)

Processing files:  96%|███████████████████████████████████████████████▉  |  ETA: 0:00:01 (29.69 ms/it)

Processing files:  96%|████████████████████████████████████████████████▎ |  ETA: 0:00:01 (29.69 ms/it)

Processing files:  97%|████████████████████████████████████████████████▋ |  ETA: 0:00:01 (29.81 ms/it)

Processing files:  98%|█████████████████████████████████████████████████▎|  ETA: 0:00:00 (29.89 ms/it)

Processing files:  99%|█████████████████████████████████████████████████▌|  ETA: 0:00:00 (29.95 ms/it)

Processing files:  99%|█████████████████████████████████████████████████▊|  ETA: 0:00:00 (29.98 ms/it)

Processing files:  99%|█████████████████████████████████████████████████▉|  ETA: 0:00:00 (30.02 ms/it)

Processing files: 100%|██████████████████████████████████████████████████| Time: 0:00:19 (29.97 ms/it)



✓ File processing complete! Combining results...
✓ Data combination complete!


Final data size: 28320979 cells, 7 variables
Creating Table from 28320979 cells with max 4 threads...


  Threading: 4 threads for 11 columns


  Max threads requested: 4
  Available threads: 4
  Using parallel processing with 4 threads


  Creating IndexedTable with 11 columns...
✓ Table created in 42.567 seconds


Memory used for data table :2.321086215786636

 GB
-------------------------------------------------------



## The record

`provenance(obj)` returns a `Provenance` struct. Its `show` is a compact human-readable block:
Mera version, simulation + output (and code), snapshot time, box / level range, scale type.

In [2]:
p = provenance(gas)
println(p)

Provenance:


  Mera version : v1.8.0
  simulation   : /Volumes/FASTStorage/Simulations/Mera-Tests/RAMSES/mw_L10
  output       : 300  (RAMSES, written 2025-06-21T18:31:24.020)
  time         : 445.89 Myr
  box / levels : L=48.0  ndim=3  levels 6–10
  scale type   : ScalesType003


The time is human-readable: physical time in Myr/Gyr for a normal run, and **redshift**
(plus expansion factor and age) for a cosmological one. `iscosmological` reports which.

In [3]:
@show iscosmological(gas.info)
@show p.time_myr        # physical snapshot time in Myr
@show p.redshift        # 0 for a non-cosmological run
@show p.aexp

iscosmological(gas.info) = false


p.time_myr = 445.8861174695
p.redshift = 0.0
p.aexp = 1.0


1.0

## What it records

Every field is read straight from the snapshot's own metadata, so two runs over the same
output produce identical provenance, safe to use in tests and comparisons.

In [4]:
@show p.mera_version
@show p.mera_build
@show p.path
@show p.output
@show p.simcode
@show p.boxlen
@show p.ndim
@show p.levelmin
@show p.levelmax
@show p.scale_type
@show p.file_ctime

p.mera_version = v"1.8.0"
p.mera_build = "1.8.0"
p.path = "/Volumes/FASTStorage/Simulations/Mera-Tests/RAMSES/mw_L10"
p.output = 300
p.simcode = "RAMSES"
p.boxlen = 48.0
p.ndim = 3
p.levelmin = 6
p.levelmax = 10
p.scale_type = :ScalesType003
p.file_ctime = Dates.DateTime("2025-06-21T18:31:24.020")


2025-06-21T18:31:24.020

## Stamping a figure or FITS header

`provenance_string` renders a one-liner, drop it into a figure caption, a log, or a `COMMENT`
card when you `savefits`.

In [5]:
s = provenance_string(gas)
println(s)

Mera v1.8.0 | mw_L10/output_00300 | 445.89 Myr | L=48.0 ndim=3 lmin=6 lmax=10 | ScalesType003


### Release build or development build

`pkgversion` reports the same `v1.8.0` whether Mera came from the registry or from a checkout
of a branch, so a notebook written against a development version would look like it was written
against the release. The version field therefore names the build whenever it can tell.

On a normal install it is just the version:

```
Mera v1.8.0 | mw_L10/output_00300 | 445.89 Myr | L=48.0 ndim=3 lmin=6 lmax=10 | ScalesType003
```

On a git checkout it carries the branch and the commit, and it marks a working tree with
uncommitted changes, because then the commit alone does not say what ran:

```
Mera v1.9.0-DEV (dev multicode @ 3a91f2c) | mw_L10/output_00300 | 445.89 Myr | ...
Mera v1.8.0 (dev revamp/2026 @ 4f2a9c1 +uncommitted) | mw_L10/output_00300 | 445.89 Myr | ...
```

This is what makes a shared script honest about what produced it. The Gallery page uses the
same line in its attribution block, so a reader can tell a released Mera from somebody's branch.

Set `MERA_PROVENANCE_PLAIN=1` to force the plain version. These pages are rendered that way, so
the examples above show a release rather than the checkout the documentation was built from.


## Where it applies

`provenance` works on **any object that carries an `InfoType`**, every data object, the
projection map, and an `InfoType` itself. Each derived result carries an `.info` field, so the
same call works on all of them.

In [6]:
# the InfoType directly
println("from InfoType : ", provenance_string(gas.info))

# a projection map (AMRMapsType)
sd = projection(gas, :sd, :Msol_pc2; center=[:bc])
println("from a map    : ", provenance_string(sd))

from InfoType : Mera v1.8.0 | mw_L10/output_00300 | 445.89 Myr | L=48.0 ndim=3 lmin=6 lmax=10 | ScalesType003
[Mera]: 2026-09-11T08:45:32.748



center: [0.5, 0.5, 0.5] 

==> [24.0 [kpc] :: 24.0 [kpc] :: 24.0 [kpc]]

domain:
xmin::xmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
ymin::ymax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
zmin::zmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]

Selected var(s)=(:sd,) 
Weighting      = :mass

Effective resolution: 1024^2
Map size: 1024 x 1024
Pixel size: 46.875 [pc]
Simulation min.: 46.875 [pc]

Available threads: 4


Requested max_threads: 4
Variables: 1 (sd)
Processing mode: Sequential (single thread)


Progress:  80%|████████████████████████████████▊        |  ETA: 0:00:00

Progress: 100%|█████████████████████████████████████████| Time: 0:00:01

from a map    : Mera v1.8.0 | mw_L10/output_00300 | 445.89 Myr | L=48.0 ndim=3 lmin=6 lmax=10 | ScalesType003


In [7]:
# particles and gravity carry the same provenance
parts = getparticles(info);
grav  = getgravity(info);
println("particles : ", provenance_string(parts))
println("gravity   : ", provenance_string(grav))

[Mera]: Get particle data: 2026-09-11T08:45:36.849



Using threaded processing with 4 threads
Key vars=(:level, :x, :y, :z, :id, :family, :tag)
Using var(s)=(1, 2, 3, 4, 7) = (:vx, :vy, :vz, :mass, :birth) 



domain:
xmin::xmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
ymin::ymax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
zmin::zmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]

Processing 640 CPU files using 4 threads
Mode: Threaded processing


Combining results from 4 thread(s)...
Found 5.445150e+05 particles
Memory used for data table :

38.428720474243164 MB
-------------------------------------------------------

[Mera]: Get gravity data: 2026-09-11T08:45:41.917



Key vars=(:level, :cx, :cy, :cz)
Using var(s)=(1, 2, 3, 4) = (:epot, :ax, :ay, :az) 

domain:
xmin::xmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
ymin::ymax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
zmin::zmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]

📊 Processing Configuration:


   Total CPU files available: 640
   Files to be processed: 640
   Compute threads: 4
   GC threads: 4



Processing files:   0%|                                                  |  ETA: N/A (  N/A  s/it)

Processing files:   1%|▍                                                 |  ETA: 0:00:46 (72.42 ms/it)

Processing files:   1%|▊                                                 |  ETA: 0:00:33 (51.73 ms/it)

Processing files:   2%|█▏                                                |  ETA: 0:00:27 (43.39 ms/it)

Processing files:   3%|█▌                                                |  ETA: 0:00:23 (37.68 ms/it)

Processing files:   4%|█▉                                                |  ETA: 0:00:22 (35.06 ms/it)

Processing files:   5%|██▍                                               |  ETA: 0:00:19 (31.98 ms/it)

Processing files:   6%|██▉                                               |  ETA: 0:00:18 (29.64 ms/it)

Processing files:   7%|███▍                                              |  ETA: 0:00:17 (28.61 ms/it)

Processing files:   8%|███▉                                              |  ETA: 0:00:16 (26.98 ms/it)

Processing files:   9%|████▌                                             |  ETA: 0:00:15 (25.81 ms/it)

Processing files:  10%|█████                                             |  ETA: 0:00:15 (25.70 ms/it)

Processing files:  11%|█████▌                                            |  ETA: 0:00:15 (25.46 ms/it)

Processing files:  12%|██████                                            |  ETA: 0:00:14 (24.96 ms/it)

Processing files:  13%|██████▋                                           |  ETA: 0:00:13 (24.26 ms/it)

Processing files:  15%|███████▎                                          |  ETA: 0:00:13 (23.63 ms/it)

Processing files:  16%|███████▊                                          |  ETA: 0:00:13 (23.27 ms/it)

Processing files:  17%|████████▍                                         |  ETA: 0:00:12 (22.80 ms/it)

Processing files:  18%|████████▉                                         |  ETA: 0:00:12 (22.71 ms/it)

Processing files:  19%|█████████▎                                        |  ETA: 0:00:12 (22.52 ms/it)

Processing files:  20%|█████████▊                                        |  ETA: 0:00:12 (22.41 ms/it)

Processing files:  21%|██████████▍                                       |  ETA: 0:00:11 (21.89 ms/it)

Processing files:  22%|███████████                                       |  ETA: 0:00:11 (21.70 ms/it)

Processing files:  23%|███████████▌                                      |  ETA: 0:00:11 (21.44 ms/it)

Processing files:  24%|████████████▏                                     |  ETA: 0:00:10 (21.33 ms/it)

Processing files:  26%|████████████▊                                     |  ETA: 0:00:10 (21.01 ms/it)

Processing files:  27%|█████████████▌                                    |  ETA: 0:00:10 (20.67 ms/it)

Processing files:  28%|██████████████                                    |  ETA: 0:00:09 (20.52 ms/it)

Processing files:  29%|██████████████▊                                   |  ETA: 0:00:09 (20.69 ms/it)

Processing files:  30%|███████████████▎                                  |  ETA: 0:00:09 (20.60 ms/it)

Processing files:  32%|███████████████▊                                  |  ETA: 0:00:09 (20.55 ms/it)

Processing files:  33%|████████████████▌                                 |  ETA: 0:00:09 (20.32 ms/it)

Processing files:  34%|█████████████████                                 |  ETA: 0:00:09 (20.34 ms/it)

Processing files:  35%|█████████████████▋                                |  ETA: 0:00:08 (20.27 ms/it)

Processing files:  37%|██████████████████▎                               |  ETA: 0:00:08 (20.19 ms/it)

Processing files:  37%|██████████████████▋                               |  ETA: 0:00:08 (20.19 ms/it)

Processing files:  38%|███████████████████▎                              |  ETA: 0:00:08 (20.13 ms/it)

Processing files:  39%|███████████████████▊                              |  ETA: 0:00:08 (20.11 ms/it)

Processing files:  40%|████████████████████▏                             |  ETA: 0:00:08 (20.22 ms/it)

Processing files:  41%|████████████████████▋                             |  ETA: 0:00:08 (20.17 ms/it)

Processing files:  42%|█████████████████████▏                            |  ETA: 0:00:07 (20.13 ms/it)

Processing files:  43%|█████████████████████▌                            |  ETA: 0:00:07 (20.26 ms/it)

Processing files:  45%|██████████████████████▍                           |  ETA: 0:00:07 (20.52 ms/it)

Processing files:  45%|██████████████████████▊                           |  ETA: 0:00:07 (20.63 ms/it)

Processing files:  46%|███████████████████████▏                          |  ETA: 0:00:07 (20.72 ms/it)

Processing files:  47%|███████████████████████▍                          |  ETA: 0:00:07 (20.85 ms/it)

Processing files:  48%|███████████████████████▊                          |  ETA: 0:00:07 (21.05 ms/it)

Processing files:  48%|████████████████████████▎                         |  ETA: 0:00:07 (21.10 ms/it)

Processing files:  49%|████████████████████████▌                         |  ETA: 0:00:07 (21.20 ms/it)

Processing files:  50%|████████████████████████▉                         |  ETA: 0:00:07 (21.26 ms/it)

Processing files:  50%|█████████████████████████▏                        |  ETA: 0:00:07 (21.41 ms/it)

Processing files:  52%|██████████████████████████                        |  ETA: 0:00:07 (21.50 ms/it)

Processing files:  52%|██████████████████████████▎                       |  ETA: 0:00:07 (21.55 ms/it)

Processing files:  53%|██████████████████████████▌                       |  ETA: 0:00:07 (21.68 ms/it)

Processing files:  54%|███████████████████████████                       |  ETA: 0:00:06 (21.73 ms/it)

Processing files:  54%|███████████████████████████▎                      |  ETA: 0:00:06 (21.85 ms/it)

Processing files:  55%|███████████████████████████▍                      |  ETA: 0:00:06 (22.04 ms/it)

Processing files:  58%|█████████████████████████████                     |  ETA: 0:00:06 (22.25 ms/it)

Processing files:  59%|█████████████████████████████▌                    |  ETA: 0:00:06 (22.24 ms/it)

Processing files:  60%|█████████████████████████████▉                    |  ETA: 0:00:06 (22.17 ms/it)

Processing files:  61%|██████████████████████████████▍                   |  ETA: 0:00:06 (22.11 ms/it)

Processing files:  62%|██████████████████████████████▉                   |  ETA: 0:00:05 (22.05 ms/it)

Processing files:  63%|███████████████████████████████▍                  |  ETA: 0:00:05 (22.09 ms/it)

Processing files:  64%|███████████████████████████████▊                  |  ETA: 0:00:05 (22.03 ms/it)

Processing files:  65%|████████████████████████████████▎                 |  ETA: 0:00:05 (21.99 ms/it)

Processing files:  66%|████████████████████████████████▊                 |  ETA: 0:00:05 (21.96 ms/it)

Processing files:  67%|█████████████████████████████████▎                |  ETA: 0:00:05 (21.89 ms/it)

Processing files:  68%|█████████████████████████████████▊                |  ETA: 0:00:05 (21.88 ms/it)

Processing files:  68%|██████████████████████████████████▎               |  ETA: 0:00:04 (21.81 ms/it)

Processing files:  69%|██████████████████████████████████▋               |  ETA: 0:00:04 (21.82 ms/it)

Processing files:  71%|███████████████████████████████████▎              |  ETA: 0:00:04 (21.67 ms/it)

Processing files:  72%|███████████████████████████████████▉              |  ETA: 0:00:04 (21.62 ms/it)

Processing files:  73%|████████████████████████████████████▌             |  ETA: 0:00:04 (21.52 ms/it)

Processing files:  74%|█████████████████████████████████████             |  ETA: 0:00:04 (21.51 ms/it)

Processing files:  75%|█████████████████████████████████████▍            |  ETA: 0:00:03 (21.50 ms/it)

Processing files:  76%|██████████████████████████████████████            |  ETA: 0:00:03 (21.42 ms/it)

Processing files:  77%|██████████████████████████████████████▋           |  ETA: 0:00:03 (21.34 ms/it)

Processing files:  79%|███████████████████████████████████████▍          |  ETA: 0:00:03 (21.21 ms/it)

Processing files:  80%|███████████████████████████████████████▉          |  ETA: 0:00:03 (21.16 ms/it)

Processing files:  81%|████████████████████████████████████████▌         |  ETA: 0:00:03 (21.12 ms/it)

Processing files:  82%|█████████████████████████████████████████▏        |  ETA: 0:00:02 (21.04 ms/it)

Processing files:  83%|█████████████████████████████████████████▋        |  ETA: 0:00:02 (20.98 ms/it)

Processing files:  84%|██████████████████████████████████████████▏       |  ETA: 0:00:02 (20.99 ms/it)

Processing files:  85%|██████████████████████████████████████████▋       |  ETA: 0:00:02 (20.96 ms/it)

Processing files:  87%|███████████████████████████████████████████▎      |  ETA: 0:00:02 (20.93 ms/it)

Processing files:  88%|███████████████████████████████████████████▉      |  ETA: 0:00:02 (20.88 ms/it)

Processing files:  89%|████████████████████████████████████████████▍     |  ETA: 0:00:02 (20.84 ms/it)

Processing files:  90%|████████████████████████████████████████████▉     |  ETA: 0:00:01 (20.86 ms/it)

Processing files:  91%|█████████████████████████████████████████████▍    |  ETA: 0:00:01 (20.85 ms/it)

Processing files:  92%|█████████████████████████████████████████████▊    |  ETA: 0:00:01 (21.18 ms/it)

Processing files:  94%|███████████████████████████████████████████████   |  ETA: 0:00:01 (21.29 ms/it)

Processing files:  95%|███████████████████████████████████████████████▍  |  ETA: 0:00:01 (21.27 ms/it)

Processing files:  95%|███████████████████████████████████████████████▊  |  ETA: 0:00:01 (21.30 ms/it)

Processing files:  96%|████████████████████████████████████████████████  |  ETA: 0:00:01 (21.36 ms/it)

Processing files:  97%|████████████████████████████████████████████████▍ |  ETA: 0:00:00 (21.41 ms/it)

Processing files:  98%|████████████████████████████████████████████████▊ |  ETA: 0:00:00 (21.43 ms/it)

Processing files:  98%|█████████████████████████████████████████████████ |  ETA: 0:00:00 (21.46 ms/it)

Processing files:  99%|█████████████████████████████████████████████████▌|  ETA: 0:00:00 (21.49 ms/it)

Processing files:  99%|█████████████████████████████████████████████████▊|  ETA: 0:00:00 (21.51 ms/it)

Processing files: 100%|██████████████████████████████████████████████████| Time: 0:00:13 (21.55 ms/it)



✓ File processing complete! Combining results...
✓ Data combination complete!


Final data size: 28320979 cells, 4 variables
Creating Table from 28320979 cells with max 4 threads...
   Threading: 4 threads for 8 columns


   Max threads requested: 4
   Available threads: 4
   Using parallel processing with 4 threads


   Creating IndexedTable with 8 columns...
✓ Table created in 4.26 seconds


Memory used for data table :1.6880627572536469 GB
-------------------------------------------------------

particles : Mera v1.8.0 | mw_L10/output_00300 | 445.89 Myr | L=48.0 ndim=3 lmin=6 lmax=10 | ScalesType003
gravity   : Mera v1.8.0 | mw_L10/output_00300 | 445.89 Myr | L=48.0 ndim=3 lmin=6 lmax=10 | ScalesType003


## Deterministic

The record depends on the snapshot's own metadata and on the Mera build, never on the wall clock,
so two independent reads of the same output in the same session produce identical provenance. That
is what makes it safe to compare in a test.


In [8]:
p2 = provenance(gethydro(info))
println("identical to first read : ", provenance_string(p2) == provenance_string(p))

[Mera]: Get hydro data: 2026-09-11T08:46:01.581

Key vars=(:level, :cx, :cy, :cz)
Using var(s)=(1, 2, 3, 4, 5, 6, 7) = (:rho, :vx, :vy, :vz, :p, :scalar_00, :scalar_01) 

domain:
xmin::xmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
ymin::ymax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]
zmin::zmax: 0.0 :: 1.0  	==> 0.0 [kpc] :: 48.0 [kpc]

📊 Processing Configuration:
   Total CPU files available: 640
   Files to be processed: 640
   Compute threads: 4
   GC threads: 4



Processing files:   0%|                                                  |  ETA: N/A (  N/A  s/it)

Processing files:   1%|▎                                                 |  ETA: 0:00:39 (61.51 ms/it)

Processing files:   2%|█▏                                                |  ETA: 0:00:27 (43.17 ms/it)

Processing files:   3%|█▌                                                |  ETA: 0:00:25 (40.08 ms/it)

Processing files:   4%|█▉                                                |  ETA: 0:00:23 (37.44 ms/it)

Processing files:   4%|██▎                                               |  ETA: 0:00:22 (36.21 ms/it)

Processing files:   5%|██▍                                               |  ETA: 0:00:22 (36.21 ms/it)

Processing files:   5%|██▊                                               |  ETA: 0:00:21 (35.31 ms/it)

Processing files:   6%|███                                               |  ETA: 0:00:21 (34.61 ms/it)

Processing files:   7%|███▍                                              |  ETA: 0:00:20 (33.77 ms/it)

Processing files:   8%|███▉                                              |  ETA: 0:00:19 (31.54 ms/it)

Processing files:   9%|████▎                                             |  ETA: 0:00:18 (30.85 ms/it)

Processing files:  10%|████▊                                             |  ETA: 0:00:17 (29.58 ms/it)

Processing files:  10%|█████▎                                            |  ETA: 0:00:17 (29.48 ms/it)

Processing files:  11%|█████▊                                            |  ETA: 0:00:16 (28.78 ms/it)

Processing files:  12%|██████▎                                           |  ETA: 0:00:16 (28.00 ms/it)

Processing files:  13%|██████▊                                           |  ETA: 0:00:15 (27.37 ms/it)

Processing files:  14%|███████                                           |  ETA: 0:00:15 (27.31 ms/it)

Processing files:  15%|███████▍                                          |  ETA: 0:00:15 (27.47 ms/it)

Processing files:  16%|███████▉                                          |  ETA: 0:00:14 (26.85 ms/it)

Processing files:  17%|████████▍                                         |  ETA: 0:00:14 (26.84 ms/it)

Processing files:  18%|████████▉                                         |  ETA: 0:00:14 (26.57 ms/it)

Processing files:  18%|█████████▎                                        |  ETA: 0:00:14 (26.42 ms/it)

Processing files:  19%|█████████▋                                        |  ETA: 0:00:14 (26.31 ms/it)

Processing files:  20%|██████████▏                                       |  ETA: 0:00:13 (25.97 ms/it)

Processing files:  21%|██████████▋                                       |  ETA: 0:00:13 (25.57 ms/it)

Processing files:  22%|███████████▏                                      |  ETA: 0:00:13 (26.72 ms/it)

Processing files:  24%|████████████                                      |  ETA: 0:00:13 (26.39 ms/it)

Processing files:  25%|████████████▌                                     |  ETA: 0:00:13 (26.32 ms/it)

Processing files:  27%|█████████████▋                                    |  ETA: 0:00:12 (25.96 ms/it)

Processing files:  28%|██████████████                                    |  ETA: 0:00:12 (25.96 ms/it)

Processing files:  29%|██████████████▌                                   |  ETA: 0:00:12 (25.56 ms/it)

Processing files:  30%|███████████████▏                                  |  ETA: 0:00:11 (25.36 ms/it)

Processing files:  31%|███████████████▌                                  |  ETA: 0:00:11 (25.35 ms/it)

Processing files:  32%|████████████████▏                                 |  ETA: 0:00:11 (25.20 ms/it)

Processing files:  33%|████████████████▌                                 |  ETA: 0:00:11 (24.98 ms/it)

Processing files:  34%|█████████████████                                 |  ETA: 0:00:11 (24.93 ms/it)

Processing files:  35%|█████████████████▍                                |  ETA: 0:00:10 (25.06 ms/it)

Processing files:  36%|██████████████████                                |  ETA: 0:00:10 (24.97 ms/it)

Processing files:  37%|██████████████████▌                               |  ETA: 0:00:10 (24.90 ms/it)

Processing files:  38%|██████████████████▉                               |  ETA: 0:00:10 (25.15 ms/it)

Processing files:  38%|███████████████████▎                              |  ETA: 0:00:10 (25.10 ms/it)

Processing files:  39%|███████████████████▋                              |  ETA: 0:00:10 (25.07 ms/it)

Processing files:  40%|███████████████████▉                              |  ETA: 0:00:10 (25.15 ms/it)

Processing files:  41%|████████████████████▎                             |  ETA: 0:00:10 (25.06 ms/it)

Processing files:  41%|████████████████████▊                             |  ETA: 0:00:09 (25.04 ms/it)

Processing files:  42%|█████████████████████                             |  ETA: 0:00:09 (25.07 ms/it)

Processing files:  43%|█████████████████████▍                            |  ETA: 0:00:09 (25.09 ms/it)

Processing files:  43%|█████████████████████▋                            |  ETA: 0:00:09 (25.28 ms/it)

Processing files:  44%|██████████████████████                            |  ETA: 0:00:09 (25.30 ms/it)

Processing files:  45%|██████████████████████▍                           |  ETA: 0:00:09 (25.71 ms/it)

Processing files:  46%|██████████████████████▉                           |  ETA: 0:00:09 (25.93 ms/it)

Processing files:  46%|███████████████████████▎                          |  ETA: 0:00:09 (25.97 ms/it)

Processing files:  47%|███████████████████████▌                          |  ETA: 0:00:09 (26.59 ms/it)

Processing files:  48%|███████████████████████▊                          |  ETA: 0:00:09 (26.81 ms/it)

Processing files:  48%|████████████████████████                          |  ETA: 0:00:09 (26.90 ms/it)

Processing files:  49%|████████████████████████▍                         |  ETA: 0:00:09 (26.93 ms/it)

Processing files:  49%|████████████████████████▋                         |  ETA: 0:00:09 (27.06 ms/it)

Processing files:  50%|████████████████████████▊                         |  ETA: 0:00:09 (27.25 ms/it)

Processing files:  50%|█████████████████████████▏                        |  ETA: 0:00:09 (27.22 ms/it)

Processing files:  51%|█████████████████████████▌                        |  ETA: 0:00:09 (28.00 ms/it)

Processing files:  52%|█████████████████████████▊                        |  ETA: 0:00:09 (28.10 ms/it)

Processing files:  52%|██████████████████████████▏                       |  ETA: 0:00:09 (28.28 ms/it)

Processing files:  53%|██████████████████████████▌                       |  ETA: 0:00:09 (28.28 ms/it)

Processing files:  54%|██████████████████████████▊                       |  ETA: 0:00:09 (28.87 ms/it)

Processing files:  55%|███████████████████████████▋                      |  ETA: 0:00:08 (29.07 ms/it)

Processing files:  56%|███████████████████████████▊                      |  ETA: 0:00:08 (29.50 ms/it)

Processing files:  56%|████████████████████████████▎                     |  ETA: 0:00:08 (29.46 ms/it)

Processing files:  57%|████████████████████████████▌                     |  ETA: 0:00:08 (29.43 ms/it)

Processing files:  58%|████████████████████████████▉                     |  ETA: 0:00:08 (29.50 ms/it)

Processing files:  59%|█████████████████████████████▊                    |  ETA: 0:00:08 (29.26 ms/it)

Processing files:  60%|██████████████████████████████▏                   |  ETA: 0:00:07 (29.31 ms/it)

Processing files:  62%|██████████████████████████████▊                   |  ETA: 0:00:07 (29.19 ms/it)

Processing files:  63%|███████████████████████████████▍                  |  ETA: 0:00:07 (29.10 ms/it)

Processing files:  63%|███████████████████████████████▋                  |  ETA: 0:00:07 (29.11 ms/it)

Processing files:  64%|████████████████████████████████▏                 |  ETA: 0:00:07 (28.95 ms/it)

Processing files:  65%|████████████████████████████████▌                 |  ETA: 0:00:06 (28.96 ms/it)

Processing files:  66%|████████████████████████████████▉                 |  ETA: 0:00:06 (28.90 ms/it)

Processing files:  67%|█████████████████████████████████▎                |  ETA: 0:00:06 (28.83 ms/it)

Processing files:  68%|█████████████████████████████████▊                |  ETA: 0:00:06 (28.76 ms/it)

Processing files:  69%|██████████████████████████████████▎               |  ETA: 0:00:06 (28.62 ms/it)

Processing files:  70%|██████████████████████████████████▉               |  ETA: 0:00:06 (28.53 ms/it)

Processing files:  71%|███████████████████████████████████▌              |  ETA: 0:00:05 (28.35 ms/it)

Processing files:  72%|████████████████████████████████████              |  ETA: 0:00:05 (28.23 ms/it)

Processing files:  73%|████████████████████████████████████▍             |  ETA: 0:00:05 (28.13 ms/it)

Processing files:  74%|█████████████████████████████████████             |  ETA: 0:00:05 (28.04 ms/it)

Processing files:  75%|█████████████████████████████████████▍            |  ETA: 0:00:05 (28.10 ms/it)

Processing files:  76%|█████████████████████████████████████▉            |  ETA: 0:00:04 (27.99 ms/it)

Processing files:  77%|██████████████████████████████████████▍           |  ETA: 0:00:04 (27.85 ms/it)

Processing files:  78%|██████████████████████████████████████▉           |  ETA: 0:00:04 (27.76 ms/it)

Processing files:  78%|███████████████████████████████████████▎          |  ETA: 0:00:04 (27.71 ms/it)

Processing files:  80%|███████████████████████████████████████▉          |  ETA: 0:00:04 (27.57 ms/it)

Processing files:  80%|████████████████████████████████████████▎         |  ETA: 0:00:03 (27.52 ms/it)

Processing files:  81%|████████████████████████████████████████▊         |  ETA: 0:00:03 (27.41 ms/it)

Processing files:  82%|█████████████████████████████████████████▏        |  ETA: 0:00:03 (27.41 ms/it)

Processing files:  83%|█████████████████████████████████████████▋        |  ETA: 0:00:03 (27.34 ms/it)

Processing files:  84%|██████████████████████████████████████████        |  ETA: 0:00:03 (27.33 ms/it)

Processing files:  85%|██████████████████████████████████████████▍       |  ETA: 0:00:03 (27.28 ms/it)

Processing files:  86%|██████████████████████████████████████████▊       |  ETA: 0:00:03 (27.19 ms/it)

Processing files:  86%|███████████████████████████████████████████▎      |  ETA: 0:00:02 (27.17 ms/it)

Processing files:  88%|███████████████████████████████████████████▊      |  ETA: 0:00:02 (27.06 ms/it)

Processing files:  88%|████████████████████████████████████████████      |  ETA: 0:00:02 (27.10 ms/it)

Processing files:  89%|████████████████████████████████████████████▍     |  ETA: 0:00:02 (27.10 ms/it)

Processing files:  89%|████████████████████████████████████████████▊     |  ETA: 0:00:02 (27.12 ms/it)

Processing files:  90%|█████████████████████████████████████████████▏    |  ETA: 0:00:02 (27.06 ms/it)

Processing files:  91%|█████████████████████████████████████████████▌    |  ETA: 0:00:02 (27.11 ms/it)

Processing files:  92%|██████████████████████████████████████████████▏   |  ETA: 0:00:01 (27.00 ms/it)

Processing files:  93%|██████████████████████████████████████████████▌   |  ETA: 0:00:01 (26.96 ms/it)

Processing files:  94%|██████████████████████████████████████████████▉   |  ETA: 0:00:01 (27.20 ms/it)

Processing files:  94%|███████████████████████████████████████████████▎  |  ETA: 0:00:01 (27.19 ms/it)

Processing files:  95%|███████████████████████████████████████████████▌  |  ETA: 0:00:01 (27.18 ms/it)

Processing files:  96%|███████████████████████████████████████████████▊  |  ETA: 0:00:01 (27.18 ms/it)

Processing files:  96%|████████████████████████████████████████████████▏ |  ETA: 0:00:01 (27.24 ms/it)

Processing files:  97%|████████████████████████████████████████████████▌ |  ETA: 0:00:01 (27.27 ms/it)

Processing files:  98%|█████████████████████████████████████████████████▏|  ETA: 0:00:00 (27.52 ms/it)

Processing files:  99%|█████████████████████████████████████████████████▎|  ETA: 0:00:00 (27.61 ms/it)

Processing files:  99%|█████████████████████████████████████████████████▊|  ETA: 0:00:00 (27.62 ms/it)

Processing files:  99%|█████████████████████████████████████████████████▉|  ETA: 0:00:00 (27.66 ms/it)

Processing files: 100%|██████████████████████████████████████████████████| Time: 0:00:17 (27.62 ms/it)



✓ File processing complete! Combining results...
✓ Data combination complete!


Final data size: 28320979 cells, 7 variables
Creating Table from 28320979 cells with max 4 threads...
  Threading: 4 threads for 11 columns
  Max threads requested: 4
  Available threads: 4
  Using parallel processing with 4 threads


  Creating IndexedTable with 11 columns...
✓ Table created in 45.671 seconds


Memory used for data table :2.321086215786636

 GB
-------------------------------------------------------

identical to first read : true


See also `getinfo` (the `InfoType` provenance is read from), `savefits` (the provenance
string makes a good FITS header comment), and the MERA-Files page (the `scale_type` version
matters when loading older files).